name: Create production promotion pull request
on:
  pull_request:
    branches:
    - main

jobs:
  compare-changes:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install VGS CLI
        run: |
          pip3 install vgs-cli
      - name: Diff Vault config
        run: |
          for path in $(ls live/tnt*yaml sandbox/tnt*yaml  2> /dev/null);
          do
            file=${path#*/}
            vault=${file%%.*}
            echo Comparing route: $path
            vgs get routes --vault ${vault} > ${path}.applied;
            diff -u ${path}.applied ${path} || echo "found a diff"
          done
        env:
          VGS_CLIENT_ID: ${{ secrets.VGS_CLIENT_ID }}
          VGS_CLIENT_SECRET: ${{ secrets.VGS_CLIENT_SECRET }}
